[versions]
agp = "8.11.0"
kotlin = "2.2.0"
android-minSdk = "24"
android-compileSdk = "34"
kotlinx-coroutines = "1.10.2"
kotlinx-io = "0.8.0"
okio = "3.13.0"
eclipse-collections = "11.1.0"
clikt = "5.0.3"
javacv = "1.5.12"
vanniktech-mavenPublish = "0.33.0"
gradleShadow = "8.3.8"
graalvmNative = "0.10.6"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-io-okio = { module = "org.jetbrains.kotlinx:kotlinx-io-okio", version.ref = "kotlinx-io" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-wasifilesystem = { module = "com.squareup.okio:okio-wasifilesystem", version.ref = "okio" }
eclipse-collections = { module = "org.eclipse.collections:eclipse-collections", version.ref = "eclipse-collections" }
eclipse-collections-api = { module = "org.eclipse.collections:eclipse-collections-api", version.ref = "eclipse-collections" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
javacv = { module = "org.bytedeco:javacv-platform", version.ref = "javacv" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-mavenPublish" }
gradleShadow = { id = "com.gradleup.shadow", version.ref = "gradleShadow" }
graalvmNative = { id = "org.graalvm.buildtools.native", version.ref = "graalvmNative" }
